apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: es01
  name: es01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es01
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/elastic: "true"
        io.kompose.service: es01
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
              value: es-docker-cluster
            - name: discovery.type
              value: single-node
            - name: network.bind_host
              value: ' 0.0.0.0'
            - name: network.host
              value: ' 0.0.0.0'
            - name: node.name
              value: es01
          image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
          name: es01
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data01
      restartPolicy: Always
      volumes:
        - name: data01
          persistentVolumeClaim:
            claimName: data01
status: {}
