apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: qa-api1
  name: qa-api1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qa-api1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/elastic: "true"
        io.kompose.service: qa-api1
    spec:
      containers:
        - image: triongenz/qa:v2
          name: qaapi
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /code
              name: qa-api1-claim0
      restartPolicy: Always
      volumes:
        - name: qa-api1-claim0
          persistentVolumeClaim:
            claimName: qa-api1-claim0
status: {}
