
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EWXhOakEzTWpnd00xb1hEVE15TURZeE16QTNNamd3TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFVhCm5WeEN1am84S0lXb3ppa1oram5OK3hYUzFMQlhYU0o5RDJJb1h1Z3VDdEg1N09ScXJDWk5CWXphaVJkQ3phbEsKRnF0S1ZlVEVkRVd1bE9TUTF0M0NaTUlJZ1U2RDl4TW9reGdKWWpkMnZ1VlQyODJNVllpNnlIdS9rclFoZzJhZgpMK0QyOE9DcFI3SzRFSGN0M2tlSEdvdnVkNUFNMGw2SDlWTUtjQ25TRUZJYklxM04rMzVQUnRocld0enF6TVd4CkJRM3NFMjNxMW9YcG9FQXVRaGpZd0VPbGgwd1BzODJyYmRDams4U2o4SHlPaENKSjA4RC9ZcTh6RHZ1bVpoRVYKNWRzTjdRYW5Za1pNWjhrdHF1Njk3bzZyVUp3ZU8rNHB3dFhxYWhSTEh4ZFU5VTNJeXg4cDhLOCt0MW9yYSt6bQoxOWZDb3Y0S0IzOUtkNXRuYlBjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHNnd4Qk5tenZOMm9CNE01MmpLUnY1K2phVHVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRStURE9CY1VQODltQXpQREh4YgpxNVJ6bFE0Z0l0Z0g1WC9ZbkVSVlFVYzlKZmxwVjRsRVhKdTBtZ2RIOFh4cXhSaHRFcVRUTFhkTXJDQzZpMUpUCnMrd0JCRUFDQXNKRzh6MUJkWk14aUcvZmVpNlFQVmFaSWg2NDRNdnd0UiswMjZqWW1pcE9KdFl2WFVobVhjczEKSklORXlxOC9rMFovSjNiaGErSEYwaXdiTTNRSlNQUXFGY1FPUFY5WHk0VGR4NFlMYldKcTRHNlZnM2JHc25hWQpnMDRDaWkvTnR1bEJDNVdvN2N3citLQWpFSFF2UDZUZ0tMN1NzUHdtYXBpbGNkUlRIZVFyOWh0ZW9NUWh6Qmh1CkgvVy9GUkZaSzVYbXNIQVZ0TVlKRE1iS0VlM1U4WndLRVZ2SEh6Y3JhOUNHN3U1Si9ML2QzMlRHR0hlSDFaVEkKUGY4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://18790c4e-ec9b-4759-a8b7-764a36b736c6.ap-west-1.linodelke.net:443
  name: lke64047

users:
- name: lke64047-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJibXJxQUJhNnJURHoyQzZMWTd2c01ydHFZT0tILWRzaUNUYWRwUDRORTgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tdzZqZnQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYWE4ZDBkNmUtY2JiYS00MjIwLTk0NTMtNzhlMTRkMjRiNDdjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.IizKSn6YZ2vuKGE1FvbO8cmDVxwb7Cuy-wLHeVwOiCy1H_s6GuWyQT5lP4T0505gY5_QRMJLyJ08mBYoJtKJDNnocYzrGinASQUyLnOTP4gcgyIhmEHwhDE7ifPE7dfTDmkrcmjyUHJISP4dP1XBYFKyZ4BUslzCve5Zs5IMjeZavHx_hztf2gOmj5zHN8am7ak90uhI4JwC2oBje7N6LE7qtyw_5-XtFyjRgpag7OukZ-FFqKHYozulmC55fAVBhTD473qeIGyCYOCLi9aL3eGDeruxFEYSZfvT8GPxbkHTDJUim9mM8MIk_09aKT-1kh8wj4pK-9FXmBp_PBgB-w

contexts:
- context:
    cluster: lke64047
    namespace: default
    user: lke64047-admin
  name: lke64047-ctx

current-context: lke64047-ctx
